# Generated by Django 5.1.4 on 2025-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_polygon_delete_polygonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
    ]
