# Generated by Django 5.1.4 on 2025-01-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_courier_name_delete_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinates', models.JSONField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='viewer.courier')),
            ],
        ),
    ]
